let dados = [
    {
        titulo : "Pastor Alemão",
        imagem:"https://images8.alphacoders.com/996/thumb-1920-996483.jpg",
        porte:"Grande",
        cores:"A cor mais comum é o preto e castanho, mas também existem variações como preto e vermelho, cinza e preto, e até mesmo totalmente preto.",
        temperamento:"Inteligente, leal, corajoso, protetor, obediente e enérgico. São cães muito ativos e necessitam de atividades físicas e mentais regulares",
        expectativaVida: "Em média, entre 9 e 13 anos, mas pode variar dependendo dos cuidados e da genética",
        origem: "Alemanha",
        descricao : "O Pastor Alemão é uma raça canina conhecida por sua inteligência, lealdade e versatilidade. Originário da Alemanha, foi desenvolvido para o pastoreio, mas hoje é amplamente utilizado em diversas atividades, como trabalho policial, resgate e companhia. Sua aparência imponente e pelagem densa são características marcantes, assim como sua natureza protetora e energética.",
        precoMedio:"R$2,500",
        link : "https://tudosobrecachorros.com.br/pastor-alemao/",
    },
    {
        titulo: "Labrador Retriever",
        imagem: "https://th.bing.com/th/id/OIP.ILir8fXTqpJN7A1Thnu91AHaE8?rs=1&pid=ImgDetMain",
        descricao: "O Labrador Retriever é uma raça conhecida por sua natureza amigável, leal e inteligente. Originalmente criado para a caça, hoje é um dos cães de companhia mais populares do mundo. Sua pelagem curta e densa, e sua paixão por brincadeiras, o tornam um excelente companheiro para famílias.",
        porte: "Médio",
        cores: "Preto, amarelo e chocolate",
        temperamento: "Amigável, leal, brincalhão",
        expectativaVida: "10-12 anos",
        origem: "Canadá",
        precoMedio: "R$2.000",
        link: "https://tudosobrecachorros.com.br/labrador-retriever/",
        
    },
    {
        titulo: "Golden Retriever",
        imagem: "https://th.bing.com/th/id/R.cd4154f53b289788177f0be36db4a039?rik=qvl89xq83Lykqg&riu=http%3a%2f%2fwww.hdwallpaper.nu%2fwp-content%2fuploads%2f2015%2f03%2fGolden-Retriever-Playing-Among-Flowers.jpg&ehk=xoTzAF4i5ydb24I1cFrmuvuKtnSFswKDeokqqwqHpLg%3d&risl=&pid=ImgRaw&r=0",
        descricao: "O Golden Retriever é uma raça conhecida por sua beleza, inteligência e docilidade. Originalmente criado para a caça, hoje é amplamente utilizado como cão guia, de terapia e de companhia. Sua pelagem dourada e sua natureza gentil o tornam um favorito em todo o mundo.",
        porte: "Grande",
        cores: "Dourado (diferentes tonalidades)",
        temperamento: "Amigável, leal, brincalhão, paciente",
        expectativaVida: "10-12 anos",
        origem: "Escócia",
        precoMedio: "R$3.000",
        link: "https://tudosobrecachorros.com.br/golden-retriever/",
    },
    {
        titulo: "Beagle",
        imagem: "https://img1.dogthelove.com/201810/2019/0718/ff/2/203158/500x350x100x0.jpg", 
        descricao: "O Beagle é um cão de caça com faro aguçado e personalidade alegre. É muito sociável e adora brincar. Seu tamanho médio e pelagem curta facilitam os cuidados.",
        porte: "Médio",
        cores: "Tricolor (branco, preto e castanho), bicolor (branco e castanho)",
        temperamento: "Alegre, sociável, curioso, teimoso",
        expectativaVida: "12-15 anos",
        origem: "Inglaterra",
        precoMedio: "R$2.000",
        link: "https://tudosobrecachorros.com.br/beagle/",
    },
    {
        titulo: "Pitbull (American Pit Bull Terrier)",
        imagem: "https://th.bing.com/th/id/OIP.B1TazUaIsd7TudmyaVoOvgHaFk?w=626&h=471&rs=1&pid=ImgDetMain", 
        descricao: "O Pitbull, ou American Pit Bull Terrier, é uma raça conhecida por sua força, agilidade e lealdade. Apesar da má fama, é um cão amoroso e companheiro quando bem socializado. Sua aparência forte e musculosa pode ser intimidante, mas seu temperamento é geralmente gentil e brincalhão.",
        porte: "Médio",
        cores: "Várias, incluindo branco, preto, marrom, tigrado e combinações",
        temperamento: "Leal, corajoso, energético, amigável com a família",
        expectativaVida: "12-16 anos",
        origem: "Estados Unidos",
        precoMedio: "R$2.000 - R$3.000",
        link: "https://tudosobrecachorros.com.br/american-pit-bull-terrier/",
    },
    {
        titulo: "Akita Inu",
        imagem: "https://curious-world.ru/images/content/animals/11-2020/akita-inu/2.jpg",  
        descricao: "O Akita é uma raça japonesa de grande porte, conhecida por sua lealdade, coragem e independência. É um cão poderoso e dominante, mas também pode ser muito afetuoso com sua família.",
        porte: "Grande",
        cores: "Branco, vermelho, tigrado",
        temperamento: "Leal, corajoso, independente, reservado com estranhos",
        expectativaVida: "10-15 anos",
        origem: "Japão",
        precoMedio: "R$3.000 - R$4.000",
        link: "https://tudosobrecachorros.com.br/akita/",
    },
    {
        titulo: "Lulu da Pomerânia",
        imagem: "https://th.bing.com/th/id/R.edca7a1e0eff473c5a53f8d744c0c27d?rik=KiHXUnCVT4yBtg&riu=http%3a%2f%2fwww.krohotun.com%2fwp-content%2fuploads%2f2015%2f08%2frokki.jpg&ehk=mIAWGakx8I0R1XKcHYNJMpo4Le0gpB7vYf81OB8huHQ%3d&risl=&pid=ImgRaw&r=0", 
        descricao: "O Lulu da Pomerânia é uma raça de cão pequena e charmosa, também conhecida como Spitz Alemão Anão. Apesar do tamanho pequeno, ele possui uma personalidade grande e cheia de vida.",
        porte: "Pequeno",
        cores: "Branco, laranja, preto, creme, marrom",
        temperamento: "Inteligente, ativo, brincalhão, leal",
        expectativaVida: "12-16 anos",
        origem: "Pomerânia (Alemanha e Polônia)",
        precoMedio: "R$2.500 - R$4.000",
        link: "https://tudosobrecachorros.com.br/lulu-da-pomerania-spitz-alemao-anao/",
    },
    {
        titulo: "Pinscher Miniatura",
        imagem: "https://th.bing.com/th/id/OIP._cAOPqQ0sKdSkEScUaK67wHaE8?w=1024&h=684&rs=1&pid=ImgDetMain", 
        descricao: "O Pinscher Miniatura é um cão de personalidade forte e destemida, apesar do pequeno porte. É conhecido por sua inteligência e lealdade ao dono.",
        porte: "Pequeno",
        cores: "Preto e ferrugem, chocolate e ferrugem",
        temperamento: "Inteligente, leal, destemido, alerta",
        expectativaVida: "12-16 anos",
        origem: "Alemanha",
        precoMedio: "R$2.000 - R$3.500",
        link: "https://tudosobrecachorros.com.br/pinscher/",
    },
    {
        titulo: "Dachshund - O Charmoso Cão-Salsicha",
        imagem: "https://th.bing.com/th/id/R.47fb5333189afe1cc336e650e9b80fd5?rik=pXTLc9koByEHzA&riu=http%3a%2f%2fanimalsbreeds.com%2fwp-content%2fuploads%2f2014%2f07%2fDachshund-4.jpg&ehk=Ysw5DUN7htVeG1Oixl6PzpNoWpve1FjgAxcSbGeu3bY%3d&risl=&pid=ImgRaw&r=0", 
        descricao: "O Dachshund, ou salsicha, é um cão de caça com corpo alongado e pernas curtas. Apesar de sua aparência divertida, é um cão inteligente e leal.",
        porte: "Pequeno/Médio",
        cores: "Várias, incluindo preto e canela, chocolate e castanho, tricolor",
        temperamento: "Leal, inteligente, teimoso, brincalhão, caçador",
        expectativaVida: "12-16 anos",
        origem: "Alemanha",
        precoMedio: "R$2.000 - R$3.500",
        link: "https://tudosobrecachorros.com.br/dachshund/",
    },
    {
        titulo: "Chow Chow",
        imagem: "https://th.bing.com/th/id/OIP.SYuGSCsDPjcqoFLiI5-vjAAAAA?w=400&h=391&rs=1&pid=ImgDetMain", 
        descricao: "O Chow Chow é uma raça antiga, conhecida por sua pelagem espessa e língua azul. É um cão de guarda leal e independente.",
        porte: "Médio",
        cores: "Vermelho, preto, azul, creme",
        temperamento: "Independente, leal, reservado, orgulhoso",
        expectativaVida: "9-15 anos",
        origem: "China",
        precoMedio: "R$3.000 - R$5.000",
        link: "https://tudosobrecachorros.com.br/chow-chow/",
    },
    {
        titulo: "Poodle",
        imagem: "https://th.bing.com/th/id/OIP.LC_26Jkw5TAbpRlFpWjbHQAAAA?w=400&h=400&rs=1&pid=ImgDetMain", 
        descricao: "O Poodle é um cão inteligente e versátil, conhecido por sua pelagem encaracolada. É um ótimo companheiro e se adapta bem a diversos ambientes.",
        porte: "Pequeno, Médio, Grande",
        cores: "Preto, branco, abricó, creme, cinza, vermelho",
        temperamento: "Inteligente, ativo, brincalhão, leal, adaptável",
        expectativaVida: "12-15 anos",
        origem: "Alemanha",
        precoMedio: "R$2.500 - R$5.000",
        link: "https://tudosobrecachorros.com.br/poodle-gigante-medio-anao-e-toy/",
    },
    {
        titulo: "Shiba Inu",
        imagem: "https://th.bing.com/th/id/OIP.jnQ9seaaQj6A0CBzY-GPWQAAAA?w=300&h=272&rs=1&pid=ImgDetMain", 
        descricao: "O Shiba Inu é um cão japonês de personalidade forte e independente. Apesar do pequeno tamanho, é corajoso e leal.",
        porte: "Pequeno",
        cores: "Vermelho, preto e tan, sésamo, creme",
        temperamento: "Independente, leal, corajoso, teimoso",
        expectativaVida: "12-15 anos",
        origem: "Japão",
        precoMedio: "R$3.000 - R$5.000",
        link: "https://www.petz.com.br/cachorro/racas/shiba-inu/",
    },
    {
        titulo: "Yorkshire Terrier",
        imagem: "https://highlandcanine.com/wp-content/uploads/2021/05/yorkshire-terrier-sitting-on-decking-1024x682.jpg", 
        descricao: "O Yorkshire Terrier é um cão pequeno e elegante, conhecido por sua pelagem longa e sedosa. Apesar do tamanho, possui uma personalidade forte e corajosa.",
        porte: "Pequeno",
        cores: "Aço e fogo (azul acinzentado com marcações castanhas)",
        temperamento: "Inteligente, leal, ativo, teimoso, destemido",
        expectativaVida: "12-16 anos",
        origem: "Inglaterra",
        precoMedio: "R$2.500 - R$4.000",
        link: "https://tudosobrecachorros.com.br/yorkshire-terrier/",
    },
    {
        titulo: "Shih Tzu",
        imagem: "https://th.bing.com/th/id/OIP.4wGby4ZupmoAN1S4sIIB_QAAAA?w=474&h=315&rs=1&pid=ImgDetMainhttps://exemplo.com/shih_tzu.jpg", 
        descricao: "O Shih Tzu é um cão de companhia pequeno e charmoso, conhecido por sua pelagem longa e sedosa. É um cão dócil e amoroso.",
        porte: "Pequeno",
        cores: "Várias cores sólidas ou combinadas, como branco, preto, dourado, cinza",
        temperamento: "Dócil, amoroso, paciente, adaptável",
        expectativaVida: "10-16 anos",
        origem: "China",
        precoMedio: "R$2.000 - R$3.500",
        link: "https://tudosobrecachorros.com.br/shih-tzu/",
    },
] 